# This file is automatically generated by https://github.com/Ownage-FDT/tfs-cli/blob/main/.github/scripts/homebrew-release.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/Ownage-FDT/tfs-cli/blob/main/.github/scripts/templates/homebrew-tfs.rb
class Tfs < Formula
    desc "Share files seamlessly without leaving your terminal"
    homepage "https://trytfs.com"
    url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/af5d431/tfs-v1.0.0-af5d431-darwin-x64.tar.gz"
    sha256 "378873d859086ec483193725cc40ac412d179e33085c46aaec733d644181d9ae"
    version "1.0.0"
    version_scheme 1
  
    on_macos do
      on_arm do
        url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/af5d431/tfs-v1.0.0-af5d431-darwin-arm64.tar.gz"
        sha256 "a4b2ebc888d141f4bce90771477245f9ade47ad616f204d218e829f6199e26a9"
      end
    end
  
    on_linux do
      on_intel do
        url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/af5d431/tfs-v1.0.0-af5d431-linux-x64.tar.gz"
        sha256 "6d13a9a859965620e8cb81e755fac0bb35a92b029158c9c2a4b90596eb30a82d"
      end
      on_arm do
        url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/af5d431/tfs-v1.0.0-af5d431-linux-arm.tar.gz"
        sha256 "f34328a68a9d0d00a26fd4920e26378853e0d5b39b99187d343a45d9c33d4a95"
      end
    end
  
    def install
      inreplace "bin/tfs", /^CLIENT_HOME=/, "export TFS_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
      libexec.install Dir["*"]
      bin.install_symlink libexec/"bin/tfs"
    end
  
    def caveats; <<~EOS
      To use the TFS CLI's autocomplete --
        Via homebrew's shell completion:
          1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
              NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                    and called, either explicitly or via a framework like oh-my-zsh.
          2) Then run
            $ tfs autocomplete --refresh-cache
        OR
        Use our standalone setup:
          1) Run and follow the install steps:
            $ tfs autocomplete
    EOS
    end
  
    test do
      system bin/"tfs", "version"
    end
  end