# This file is automatically generated by https://github.com/Ownage-FDT/tfs-cli/blob/main/.github/scripts/homebrew-release.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/Ownage-FDT/tfs-cli/blob/main/.github/scripts/templates/homebrew-tfs.rb
class Tfs < Formula
    desc "Share files seamlessly without leaving your terminal"
    homepage "https://trytfs.com"
    url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/b8bf911/tfs-v1.0.0-b8bf911-darwin-x64.tar.gz"
    sha256 "5ae99e0ce93b0abf9c998ad488ae058814dc5112a31f930243734de328ab5422"
    version "1.0.0"
    version_scheme 1
  
    on_macos do
      on_arm do
        url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/b8bf911/tfs-v1.0.0-b8bf911-darwin-arm64.tar.gz"
        sha256 "9e0a8f9ac168de74132224642abdcb65a8bc2c43bd4ee4be4e903c06cb9720b7"
      end
    end
  
    on_linux do
      on_intel do
        url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/b8bf911/tfs-v1.0.0-b8bf911-linux-x64.tar.gz"
        sha256 "8a898a044c5485eb91eded295e10ad564016824e55a7f0d916ce259066cf14bc"
      end
      on_arm do
        url "https://tfs-cli-assets.nyc3.digitaloceanspaces.com/versions/1.0.0/b8bf911/tfs-v1.0.0-b8bf911-linux-arm.tar.gz"
        sha256 "b29b095fbad359844fab1fb328f03e3eb6944ff178105a57d6d7fe363cde7215"
      end
    end
  
    def install
      inreplace "bin/tfs", /^CLIENT_HOME=/, "export TFS_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
      libexec.install Dir["*"]
      bin.install_symlink libexec/"bin/tfs"
    end
  
    def caveats; <<~EOS
      To use the TFS CLI's autocomplete --
        Via homebrew's shell completion:
          1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
              NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                    and called, either explicitly or via a framework like oh-my-zsh.
          2) Then run
            $ tfs autocomplete --refresh-cache
        OR
        Use our standalone setup:
          1) Run and follow the install steps:
            $ tfs autocomplete
    EOS
    end
  
    test do
      system bin/"tfs", "version"
    end
  end