name: CI

on: push

jobs:
  test-homebrew:
    name: Test Homebrew
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Cleanup Homebrew
        run: brew cleanup
      - name: Run Tests
        run: ./.github/scripts/test
